"use strict"

import "./styles/global.css"
import "./styles/utils.css"
import "./styles/card.css"
import "./styles/data.css"
import "./styles/history.css"
import "./styles/input.css"
import "./styles/logo.css"
import "./styles/progress.css"